import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/ui/NavBar";
import { Montserrat_Alternates } from "next/font/google";

export const metadata: Metadata = {
  title: "Pilcheria online",
  description: "Generated by create next app",
};
const siteFont = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["500", "700"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={siteFont.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
